---
title: "analysis"
output: html_document
date: '2022-06-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message = FALSE}
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
library(class)
library(data.table)
library(AICcmodavg)
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
```

```{r load data}
#Load data
list_df <- list.files("./data/spike data", pattern="*.csv", full.names=TRUE)
ldf <- lapply(list_df, read.csv)
```

```{r distance calculations}
if (file.exists("./data/wells distance.csv")){
  
  well_dist <- read.csv("./data/wells distance.csv")
  well_dist <- as.data.frame(lapply(well_dist, as.character))
  well_dist$distance <- as.numeric(well_dist$distance)
  
} else {
  # Create data frame with electrode place when "11" is in (0,0)
  well <- data.frame(matrix(ncol = 3, nrow = 0))
  
  x <- 0
  
  for (i in 1:4){
    y <- 0
    for (j in 1:4){
      well <- rbind(well, c(toString(i * 10 + j), x, y))
      y <- y + 350
    }
    x <- x + 350
  }
  
  colnames(well) <- c("Electrode", "x", "y")
  
  # Create data frame with the distance between every pair of electrodes
  well_dist <- data.frame(as.matrix(ceiling(dist(cbind(well$x, well$y)))))
  colnames(well_dist) <- well$Electrode
  well_dist["Electrode"] <- well$Electrode
  
  well_dist <- well_dist %>% select(1:16) %>% 
    mutate(row.1 = 1:nrow(well_dist)) %>% 
    mutate(elec2 = well_dist$Electrode[row_number()]) %>%
    pivot_longer(names_to="elec1", values_to="distance", cols=1:16) %>% 
    select(elec2, elec1, distance)
  
  # Remove duplicates such as (11, 12), (12, 11)
  well_dist <- well_dist %>% 
    mutate(dup = !duplicated(t(apply(well_dist, 1, sort)))) %>%
    filter(dup) %>% select(c("elec1", "elec2", "distance"))
  
  # Create and save a .csv file for future use
  write.csv(well_dist,"./data/wells distance.csv", row.names = FALSE)
}
```

```{r find wells and treatments, warning=FALSE}
if (file.exists("./data/wells and treatment.csv")){
  well_treat <- read.csv("./data/wells and treatment.csv")
} else {
  # Load one of the data files (arbitrarily) to extract the well information chart
  well_treat <- read.csv(file = "./data/spike data/ac div16(000)_spike_list.csv")
  
  # Find the chart in the file
  rnom <- as.numeric(which(well_treat == "Well Information"))
  well_treat <- fread(file = "./data/spike data/ac div16(000)_spike_list.csv", skip=rnom)
  
  
  # Select only well ID and treatment given
  well_treat <- well_treat[which(well_treat$`Well Information` == "Well" | 
            well_treat$`Well Information` == "Treatment"),]
  
  # Transpose to a longer data frame and fix labeling
  well_treat <- data.frame(t(well_treat[,2:ncol(well_treat)]))
  rownames(well_treat) <- seq(1:nrow(well_treat))
  colnames(well_treat) <- c("Well", "Treatment")
  
  # Filter inactive wells
  well_treat <- well_treat[well_treat$Treatment != "Inactive",]
  
  # Create and save a .csv file for future use
  write.csv(well_treat,"./data/wells and treatment.csv", row.names = FALSE)
}
```

```{r clean the data, message=FALSE}
remove_inactive <- function(df){
  df <- df[c(3,4,5)]
  df <- drop_na(df)
  #only the first 11 minutes
  df<- df %>% filter(df$Time..s.<=660) 
  df <- df[df$Electrode %like% paste(well_treat$Well, collapse = "|"),] 
  df$Time..s. <- as.numeric(df$Time..s.)
  return(df)
}

sep_wells <- function(df){
  df <- separate(df, col = "Electrode",
           into = c("Well", "Electrode"),
           sep = "_")
  return(df)
}

ldf <- lapply(ldf, remove_inactive)
ldf <- lapply(ldf, sep_wells)
```

```{r correlation matrix per time period, message=FALSE}
# Find correlation matrix for each well per each time period
find_corr_mat <- function(file_df, well_id, file_id){
  
  well_df <- filter(file_df, file_df$Well == well_id)
  elec_lst <- split(well_df, f = well_df$Electrode)
  
  # One or less electrodes sent signal for specific well
  if (dim(well_df) == 0 || length(elec_lst) <= 1){
    
    df <- data.frame("distance" = unique(well_dist$distance),
                     "well_id" = well_id,
                     "file_id" = file_id,
                     "corr" = 0)

    if (length(elec_lst) == 1){
      df [which("distance" == 0),"corr"] <- 1
    }

    return(df)
    }
  
  # Prepare data for merge
  neat_df <- function(df){
    name <- df$Electrode[1]
    df[,"id"] <- 1:nrow(df)
    df <- df[,c("id", "Time..s.")]
    colnames(df) <- c("id", name)
    return(df)
    }
  
  elec_lst <- lapply(elec_lst, neat_df)
  df <- Reduce(function(x, y) merge(x, y, by = 'id', all = TRUE), elec_lst)
  
  # Calculate the correlation matrix for this well
  corr_mat <- cor(df[,!(colnames(df) %like% "id")],
                  method = "pearson", 
                  use="pairwise.complete.obs")
  
  corr_mat[is.na(corr_mat)] <- 0
  
  # Convert correlation matrix to df
  corr <- as.data.frame(corr_mat)
  corr$elec2 <- row.names(corr)
  corr <- pivot_longer(data = corr, 
                       names_to = "elec1", 
                       values_to = "corr", 
                       cols=-elec2)
  
  # Add missing electrodes and distance
  corr <- left_join(well_dist, corr, by=c("elec1", "elec2"))

  corr[,"well_id"] <- well_id
  corr[,"file_id"] <- file_id
  
  corr$corr[is.na(corr$corr)] <- 0
  
  # Calculate mean correlation for each distance
  corr <- corr %>% group_by(distance, well_id, file_id) %>%
  mutate(corr = as.numeric(corr)) %>%
  summarise_at(vars(corr), mean)

  return(corr)
  }

# Correlation df for a given well
f1 <- function(well_id) {
  x <- sapply(seq(1:length(ldf)), function(file_id) find_corr_mat(ldf[[file_id]]
                                                        ,well_id,
                                                        file_id),
              simplify = FALSE)
  return(rbindlist(x))
  }

# Correlation df of every well
corr_df <- rbindlist(sapply(well_treat$Well, f1, simplify = FALSE))
```

```{r mean correlation by distance}
corr_df$corr[is.na(corr_df$corr)] <- 0

# Add treatment column
corr_df <- corr_df %>% rowwise() %>%
  mutate(treatment = well_treat$Treatment[well_treat$Well == well_id])

corr_df <- corr_df %>% group_by(distance, treatment, file_id) %>%
  summarise_at(vars(corr), mean)
```

```{r prepare data for ANOVA tests}
tmp <- corr_df
tmp$file_id <- as.numeric(tmp$file_id)

tmp <- tmp %>% mutate(time_p = case_when(file_id == 1 ~ "Before",
                                         between(file_id, 2, 6) ~ "Right After",
                                         file_id >= 7 ~ "Over Night"))

tmp <- tmp[, c("treatment", "distance", "corr", "time_p")]
```

```{r two-way ANOVA}
tmp$distance <- as.factor(tmp$distance)
additive <-  aov(corr ~ treatment + distance, tmp)
interaction <-  aov(corr ~ treatment * distance, tmp)
blocking <- aov(corr ~ treatment * distance + time_p + treatment:time_p, tmp)

summary(additive)
summary(interaction)
summary(blocking)
```

```{r AIC to find best fitted ANOVA}
model.set <- list(additive, interaction, blocking)
model.names <- c("additive", "interaction", "blocking")

aictab(model.set, modnames = model.names)
```

```{r}
tbl1 <- as.data.frame(TukeyHSD(blocking, which = c("treatment"))[[1]])
tbl2 <- as.data.table(TukeyHSD(blocking, which = c("treatment:time_p"))[[1]], 
                                  keep.rownames = TRUE)
tbl2 <- separate(tbl2,
                             col = 1,
                             into = c("t1", "t2"),
                             sep = "-") %>% 
  separate(col = 2,
           into = c("treatment2", "time2"),
           sep = ":") %>% 
  separate(col = 1,
           into= c("treatment1", "time1"), 
           sep = ":")

tbl2 <- tbl2[treatment1 == treatment2 & 
               (time1 != "Right After" & time2 != "Right After"), c(1,2,4,5,6,7,8)]
tbl2 <- tbl2[order(tbl2, treatment1),]

tbl1
tbl2
```

```{r graph per treatment, fig.height=2, fig.width=7, message=FALSE}
fig1_data <- tmp %>% 
  group_by(time_p, treatment, distance) %>% 
  summarise_at(vars(corr), mean)

fig1 <- ggplot(transform(fig1_data,
                         treatment = factor(treatment,levels = c("Control","AP5","FGL")),
                         time_p = factor(time_p,levels = c("Before","Right After","Over Night"))),
               aes(x=distance,
                   y=corr,
                   color=time_p,
                   group=time_p)) +
  geom_line()+
  facet_wrap(~treatment)+
  theme_ipsum()+
  labs(
    x="Distance(μm)",
    y="Correlation",
    color="Time")+
  geom_point() + 
  theme(
    plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
    legend.position = "top",
    legend.key.size = unit(1, "lines"),
    legend.title = element_blank(),
    legend.box = "verical", 
    axis.text.x = element_text(angle = 60, hjust = 1, size = 7),
    ) + 
  scale_color_brewer(palette = "Set2")

fig1
```
