---
title: "corr"
output: html_document
date: '2022-06-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message = FALSE}
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
```

```{r}
#Load data
bl_000 <- read.csv(file = "./data/bl div16(000)_spike_list.csv")
```

```{r}
get_petri <- function(df){
  df_res <- df[c(3,4,5)]
  df_res <- separate(df_res, col = "Electrode",
           into = c("Petri", "Electrode"),
           sep = "_")
  df_res <- drop_na(df_res)
  return(df_res)
}

#Prepare data 
bl_000_corr <- get_petri(bl_000)
bl_000_corr$Time..s. <- as.numeric(bl_000_corr$Time..s.)
# bl_000_corr$Electrode <- as.numeric(bl_000_corr$Electrode)

bl_000_corr <- drop_na(bl_000_corr)
```

<!-- ```{r} -->
<!-- bl_000_corr$Electrode <- sapply(bl_000_corr$Electrode, function(x){ -->
<!--   switch (x, -->
<!--   "11" = 1, -->
<!--   "12" = 2, -->
<!--   "13" = 3, -->
<!--   "14" = 4, -->
<!--   "21" = 5, -->
<!--   "22" = 6, -->
<!--   "23" = 7, -->
<!--   "24" = 8, -->
<!--   "31" = 9, -->
<!--   "32" = 10, -->
<!--   "33" = 11, -->
<!--   "34" = 12, -->
<!--   "41" = 13, -->
<!--   "42" = 14, -->
<!--   "43" = 15, -->
<!--   "44" = 16 -->
<!-- ) -->
<!-- } -->
<!-- ) -->
<!-- ``` -->

```{r}
p_A6 <- filter(bl_000_corr, bl_000_corr$Petri == "A6")
elec_lst <- split(p_A6, f = p_A6$Electrode)

e_11 <- elec_lst$`11`[,c("Electrode", "Time..s.", "Amplitude..mV.")]
e_12 <- elec_lst$`12`[,c("Electrode", "Time..s.", "Amplitude..mV.")]

if (nrow(e_11) > nrow(e_12)){
  e_12[nrow(e_12):nrow(e_11),] <- c(12, NA, 0)
} else {
  e_11[nrow(e_12):nrow(e_11),] <- c(11, NA, 0)
}

e_11
e_12
  
res <- ccf(x = e_11$Time..s., y=e_12$Time..s., na.action = na.pass)
res
```

```{r}
p_A6 <- filter(bl_000_corr, bl_000_corr$Petri == "A6")
p_A6 <- p_A6 %>% head(10)
elec_lst <- split(p_A6, f = p_A6$Electrode)

find_corr_mat <- function(elec_lst){
    df <- elec_lst$`11`[,c("Time..s.", "Petri")]
    for (i in elec_lst[2:length(elec_lst)]){
    tmp <- data.frame(a= i$Time..s.,
                      b = i$Petri)
    colnames(tmp) = c(i$Electrode[1], "Petri")
    df <- full_join(df, tmp, by=character())
    df <- df[, !(names(df) %in% "Petri")]
    }
    return(cor(df))
}

lst <- find_corr_mat(elec_lst)
lst
```

```{r}
p_A6 <- filter(bl_000_corr, bl_000_corr$Petri == "A6")
elec_lst <- split(p_A6, f = p_A6$Electrode)

find_corr_mat <- function(){
  elec <- sort(unique(p_A6$Electrode))
  corr_mat <- diag(16)

  for (i in 1:length(elec_lst)){
    for (j in i:length(elec_lst)){
      if (i == j){next}
      tmp1 <- elec_lst[[i]]["Time..s."]
      tmp2 <- elec_lst[[j]]["Time..s."]
      mini_corr <- full_join(tmp1, tmp2, by = character())
      mini_corr <- cor(mini_corr)
      corr_mat[i,j] <- mini_corr[1,2]
    }
  }
  
  corr_mat <- data.frame(corr_mat)
  colnames(corr_mat) <- elec

  return(corr_mat)
}

corr <- find_corr_mat()
corr
```

```{r}
p_A6 <- filter(bl_000_corr, bl_000_corr$Petri == "A6")
elec_lst <- split(p_A6, f = p_A6$Electrode)

find_corr_mat <- function(){
  df <- data.frame(id= 1)
  
  for (i in elec_lst){
    tmp <- i
    tmp[,"id"] <- 1:nrow(tmp)
    tmp <- tmp[,c("id", "Time..s.")]
    colnames(tmp) <- c("id", i$Electrode[1])
    df <- merge(df, tmp, by = "id", all = TRUE)
  }
  
  corr_mat <- cor(df[,!(colnames(df) %in% "id")], use="pairwise.complete.obs")
}

corr <- find_corr_mat()
corr
```







